// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPs__EW8DW2l-hxwgCXXh7Cd5Djl8iJQ4',
    appId: '1:210276121411:android:9031dce093f181f2548df6',
    messagingSenderId: '210276121411',
    projectId: 'analyticstest-e5676',
    storageBucket: 'analyticstest-e5676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJcoKDic2Y5Yw_cMi0PanVib8wBEaz50o',
    appId: '1:210276121411:ios:fba73448a3e21ec7548df6',
    messagingSenderId: '210276121411',
    projectId: 'analyticstest-e5676',
    storageBucket: 'analyticstest-e5676.appspot.com',
    iosBundleId: 'com.example.analyticsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJcoKDic2Y5Yw_cMi0PanVib8wBEaz50o',
    appId: '1:210276121411:ios:24b9305017fc2aa4548df6',
    messagingSenderId: '210276121411',
    projectId: 'analyticstest-e5676',
    storageBucket: 'analyticstest-e5676.appspot.com',
    iosBundleId: 'com.example.analyticsTest.RunnerTests',
  );
}
